#define RGBLIGHT_SLEEP

#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8

#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING
#define RGB_MATRIX_DEFAULT_HUE 185
#define RGB_MATRIX_DEFAULT_SAT 200
#define RGB_MATRIX_DEFAULT_SPD 35

#define DUCK_LED_INDEX 27
